# Generated by Django 4.1.4 on 2023-02-19 10:33

from django.db import migrations, models
import news_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=news_app.models.upload_to),
        ),
    ]
