# Generated by Django 4.1.4 on 2023-02-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to='news/images'),
            preserve_default=False,
        ),
    ]
